# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT

# When set to false, ignores files with "GENERATED" header, similar to golint
ignoreGeneratedHeader = true

# Disabled rules
# [rule.package-comments] is disabled because it incorrectly flags every package file as
# missing a package comment when you should only need to add a comment to one of the package files.
[rule.package-comments]
Disabled = true